# NumPy: (2024.01.10)

- **Numerical Computing:** NumPy is a Python library for numerical computations.
- **Multidimensional Arrays:** Provides `ndarray`, allowing operations on multi-dimensional arrays.
- **Efficient Operations:** Offers mathematical functions for array operations, enhancing performance.
- **Broadcasting:** Performs implicit element-wise operations on arrays of different shapes.
- **Linear Algebra:** Includes tools for matrix operations and linear algebra tasks.
- **Integration:** Often used with Pandas, Matplotlib, and other data science libraries.
- **Used in:** Data analysis, machine learning, scientific computing, and more.

In [93]:
#initialy Lets import numpy
import numpy as np

In [94]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)

In [95]:
type(arr)

numpy.ndarray

In [96]:
print(arr)

[1 2 3 4 5]


In [97]:
arr

array([1, 2, 3, 4, 5])

In [98]:
arr.shape

(5,)

In [99]:
#Multinested array

my_list1 = [1, 2, 3, 4, 5]
my_list2 = [2, 3, 4, 5, 6]
my_list3 = [9, 7, 6, 8, 9]

arr = np.array([my_list1, my_list2, my_list3]) #Converting as multidimensional array

In [100]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [101]:
#see the size of the array
arr.shape

(3, 5)

In [102]:
arr.reshape(3, 5)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [103]:
arr.reshape(1, 15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

## indexing

In [104]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
arr[0]

1

In [106]:
arr.shape

(9,)

In [107]:
multiArr = np.array([[1, 2, 3, 4, 5],
            [2, 3, 4, 5, 6],
            [9, 7, 6, 8, 9]])

In [108]:
multiArr[0][0]

1

In [109]:
multiArr[0:2, 0:2]

array([[1, 2],
       [2, 3]])

In [110]:
multiArr[1:4, 3:5]

array([[5, 6],
       [8, 9]])

In [111]:
multiArr[1:]

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [112]:
multiArr[1:3, 2:4]

array([[4, 5],
       [6, 8]])

In [113]:
multiArr[1:3, 1:4]

array([[3, 4, 5],
       [7, 6, 8]])

In [114]:
multiArr = np.arange(0, 10, 2)

In [115]:
multiArr

array([0, 2, 4, 6, 8])

In [116]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [117]:
#copy function and broadcasting
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[3:]

array([4, 5, 6, 7, 8, 9])

In [118]:
arr[3:] = 100
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [119]:
arr1 = arr
arr1[3:] = 500
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [120]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [121]:
arr1 = arr.copy()

In [122]:
print(arr)
arr1[3:] = 1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [123]:
### Some conditions very useful in Explonataty Data Analysis

val = 2
arr < 2

array([ True, False, False, False, False, False, False, False, False])

In [124]:
arr * 2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000, 1000])

In [125]:
arr / 2

array([  0.5,   1. ,   1.5, 250. , 250. , 250. , 250. , 250. , 250. ])

In [126]:
arr % 2

array([1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int32)

In [127]:
arr[arr < 3]

array([1, 2])

In [128]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [129]:
np.random.rand(3, 3)

array([[0.96616622, 0.151727  , 0.40577954],
       [0.58365635, 0.83407262, 0.01497523],
       [0.42691654, 0.9846791 , 0.92242785]])

In [130]:
np.random.randint(0, 100, 8)

array([13, 16, 25, 92, 24, 49,  7, 22])

In [131]:
np.random.randint(0, 100, 8).reshape(2, 4)

array([[44, 96, 37, 63],
       [86, 34, 56, 17]])

In [132]:
np.random.random_sample((1, 5))

array([[0.55023684, 0.84349247, 0.99963339, 0.73184969, 0.85488041]])